/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as AppRepositoriesIndexRouteImport } from './routes/_app.repositories.index'
import { Route as AppRepositoriesIdRouteImport } from './routes/_app.repositories.$id'
import { Route as AppRepositoriesIdIndexRouteImport } from './routes/_app.repositories.$id.index'
import { Route as AppRepositoriesIdArchitectureRouteImport } from './routes/_app.repositories.$id.architecture'
import { Route as AppRepositoriesIdChatRouteImport } from './routes/_app.repositories.$id.chat'
import { Route as AppRepositoriesIdDependenciesRouteImport } from './routes/_app.repositories.$id.dependencies'
import { Route as AppRepositoriesIdDocumentationRouteImport } from './routes/_app.repositories.$id.documentation'
import { Route as AppRepositoriesIdFilesRouteImport } from './routes/_app.repositories.$id.files'
import { Route as AppRepositoriesIdHealthRouteImport } from './routes/_app.repositories.$id.health'
import { Route as AppRepositoriesIdSearchRouteImport } from './routes/_app.repositories.$id.search'
import { Route as ApiPublicHooksProcessAnalysisRouteImport } from './routes/api/public/hooks/process-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesIdRoute = AppRepositoriesIdRouteImport.update({
  id: '/repositories/$id',
  path: '/repositories/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesIdIndexRoute = AppRepositoriesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRepositoriesIdRoute,
} as any)
const AppRepositoriesIdArchitectureRoute =
  AppRepositoriesIdArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AppRepositoriesIdRoute,
  } as any)
const AppRepositoriesIdChatRoute = AppRepositoriesIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRepositoriesIdRoute,
} as any)
const AppRepositoriesIdDependenciesRoute =
  AppRepositoriesIdDependenciesRouteImport.update({
    id: '/dependencies',
    path: '/dependencies',
    getParentRoute: () => AppRepositoriesIdRoute,
  } as any)
const AppRepositoriesIdDocumentationRoute =
  AppRepositoriesIdDocumentationRouteImport.update({
    id: '/documentation',
    path: '/documentation',
    getParentRoute: () => AppRepositoriesIdRoute,
  } as any)
const AppRepositoriesIdFilesRoute = AppRepositoriesIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRepositoriesIdRoute,
} as any)
const AppRepositoriesIdHealthRoute = AppRepositoriesIdHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRepositoriesIdRoute,
} as any)
const AppRepositoriesIdSearchRoute = AppRepositoriesIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRepositoriesIdRoute,
} as any)
const ApiPublicHooksProcessAnalysisRoute =
  ApiPublicHooksProcessAnalysisRouteImport.update({
    id: '/api/public/hooks/process-analysis',
    path: '/api/public/hooks/process-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/repositories/$id': typeof AppRepositoriesIdRouteWithChildren
  '/repositories/': typeof AppRepositoriesIndexRoute
  '/repositories/$id/architecture': typeof AppRepositoriesIdArchitectureRoute
  '/repositories/$id/chat': typeof AppRepositoriesIdChatRoute
  '/repositories/$id/dependencies': typeof AppRepositoriesIdDependenciesRoute
  '/repositories/$id/documentation': typeof AppRepositoriesIdDocumentationRoute
  '/repositories/$id/files': typeof AppRepositoriesIdFilesRoute
  '/repositories/$id/health': typeof AppRepositoriesIdHealthRoute
  '/repositories/$id/search': typeof AppRepositoriesIdSearchRoute
  '/api/public/hooks/process-analysis': typeof ApiPublicHooksProcessAnalysisRoute
  '/repositories/$id/': typeof AppRepositoriesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/help': typeof AppHelpRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/repositories': typeof AppRepositoriesIndexRoute
  '/repositories/$id/architecture': typeof AppRepositoriesIdArchitectureRoute
  '/repositories/$id/chat': typeof AppRepositoriesIdChatRoute
  '/repositories/$id/dependencies': typeof AppRepositoriesIdDependenciesRoute
  '/repositories/$id/documentation': typeof AppRepositoriesIdDocumentationRoute
  '/repositories/$id/files': typeof AppRepositoriesIdFilesRoute
  '/repositories/$id/health': typeof AppRepositoriesIdHealthRoute
  '/repositories/$id/search': typeof AppRepositoriesIdSearchRoute
  '/api/public/hooks/process-analysis': typeof ApiPublicHooksProcessAnalysisRoute
  '/repositories/$id': typeof AppRepositoriesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_app/repositories/$id': typeof AppRepositoriesIdRouteWithChildren
  '/_app/repositories/': typeof AppRepositoriesIndexRoute
  '/_app/repositories/$id/architecture': typeof AppRepositoriesIdArchitectureRoute
  '/_app/repositories/$id/chat': typeof AppRepositoriesIdChatRoute
  '/_app/repositories/$id/dependencies': typeof AppRepositoriesIdDependenciesRoute
  '/_app/repositories/$id/documentation': typeof AppRepositoriesIdDocumentationRoute
  '/_app/repositories/$id/files': typeof AppRepositoriesIdFilesRoute
  '/_app/repositories/$id/health': typeof AppRepositoriesIdHealthRoute
  '/_app/repositories/$id/search': typeof AppRepositoriesIdSearchRoute
  '/api/public/hooks/process-analysis': typeof ApiPublicHooksProcessAnalysisRoute
  '/_app/repositories/$id/': typeof AppRepositoriesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/activity'
    | '/dashboard'
    | '/help'
    | '/profile'
    | '/settings'
    | '/login'
    | '/register'
    | '/oauth/callback'
    | '/repositories/$id'
    | '/repositories/'
    | '/repositories/$id/architecture'
    | '/repositories/$id/chat'
    | '/repositories/$id/dependencies'
    | '/repositories/$id/documentation'
    | '/repositories/$id/files'
    | '/repositories/$id/health'
    | '/repositories/$id/search'
    | '/api/public/hooks/process-analysis'
    | '/repositories/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/activity'
    | '/dashboard'
    | '/help'
    | '/profile'
    | '/settings'
    | '/login'
    | '/register'
    | '/oauth/callback'
    | '/repositories'
    | '/repositories/$id/architecture'
    | '/repositories/$id/chat'
    | '/repositories/$id/dependencies'
    | '/repositories/$id/documentation'
    | '/repositories/$id/files'
    | '/repositories/$id/health'
    | '/repositories/$id/search'
    | '/api/public/hooks/process-analysis'
    | '/repositories/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_app/activity'
    | '/_app/dashboard'
    | '/_app/help'
    | '/_app/profile'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/oauth/callback'
    | '/_app/repositories/$id'
    | '/_app/repositories/'
    | '/_app/repositories/$id/architecture'
    | '/_app/repositories/$id/chat'
    | '/_app/repositories/$id/dependencies'
    | '/_app/repositories/$id/documentation'
    | '/_app/repositories/$id/files'
    | '/_app/repositories/$id/health'
    | '/_app/repositories/$id/search'
    | '/api/public/hooks/process-analysis'
    | '/_app/repositories/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ApiPublicHooksProcessAnalysisRoute: typeof ApiPublicHooksProcessAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/repositories/': {
      id: '/_app/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AppRepositoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$id': {
      id: '/_app/repositories/$id'
      path: '/repositories/$id'
      fullPath: '/repositories/$id'
      preLoaderRoute: typeof AppRepositoriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$id/': {
      id: '/_app/repositories/$id/'
      path: '/'
      fullPath: '/repositories/$id/'
      preLoaderRoute: typeof AppRepositoriesIdIndexRouteImport
      parentRoute: typeof AppRepositoriesIdRoute
    }
    '/_app/repositories/$id/architecture': {
      id: '/_app/repositories/$id/architecture'
      path: '/architecture'
      fullPath: '/repositories/$id/architecture'
      preLoaderRoute: typeof AppRepositoriesIdArchitectureRouteImport
      parentRoute: typeof AppRepositoriesIdRoute
    }
    '/_app/repositories/$id/chat': {
      id: '/_app/repositories/$id/chat'
      path: '/chat'
      fullPath: '/repositories/$id/chat'
      preLoaderRoute: typeof AppRepositoriesIdChatRouteImport
      parentRoute: typeof AppRepositoriesIdRoute
    }
    '/_app/repositories/$id/dependencies': {
      id: '/_app/repositories/$id/dependencies'
      path: '/dependencies'
      fullPath: '/repositories/$id/dependencies'
      preLoaderRoute: typeof AppRepositoriesIdDependenciesRouteImport
      parentRoute: typeof AppRepositoriesIdRoute
    }
    '/_app/repositories/$id/documentation': {
      id: '/_app/repositories/$id/documentation'
      path: '/documentation'
      fullPath: '/repositories/$id/documentation'
      preLoaderRoute: typeof AppRepositoriesIdDocumentationRouteImport
      parentRoute: typeof AppRepositoriesIdRoute
    }
    '/_app/repositories/$id/files': {
      id: '/_app/repositories/$id/files'
      path: '/files'
      fullPath: '/repositories/$id/files'
      preLoaderRoute: typeof AppRepositoriesIdFilesRouteImport
      parentRoute: typeof AppRepositoriesIdRoute
    }
    '/_app/repositories/$id/health': {
      id: '/_app/repositories/$id/health'
      path: '/health'
      fullPath: '/repositories/$id/health'
      preLoaderRoute: typeof AppRepositoriesIdHealthRouteImport
      parentRoute: typeof AppRepositoriesIdRoute
    }
    '/_app/repositories/$id/search': {
      id: '/_app/repositories/$id/search'
      path: '/search'
      fullPath: '/repositories/$id/search'
      preLoaderRoute: typeof AppRepositoriesIdSearchRouteImport
      parentRoute: typeof AppRepositoriesIdRoute
    }
    '/api/public/hooks/process-analysis': {
      id: '/api/public/hooks/process-analysis'
      path: '/api/public/hooks/process-analysis'
      fullPath: '/api/public/hooks/process-analysis'
      preLoaderRoute: typeof ApiPublicHooksProcessAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRepositoriesIdRouteChildren {
  AppRepositoriesIdArchitectureRoute: typeof AppRepositoriesIdArchitectureRoute
  AppRepositoriesIdChatRoute: typeof AppRepositoriesIdChatRoute
  AppRepositoriesIdDependenciesRoute: typeof AppRepositoriesIdDependenciesRoute
  AppRepositoriesIdDocumentationRoute: typeof AppRepositoriesIdDocumentationRoute
  AppRepositoriesIdFilesRoute: typeof AppRepositoriesIdFilesRoute
  AppRepositoriesIdHealthRoute: typeof AppRepositoriesIdHealthRoute
  AppRepositoriesIdSearchRoute: typeof AppRepositoriesIdSearchRoute
  AppRepositoriesIdIndexRoute: typeof AppRepositoriesIdIndexRoute
}

const AppRepositoriesIdRouteChildren: AppRepositoriesIdRouteChildren = {
  AppRepositoriesIdArchitectureRoute: AppRepositoriesIdArchitectureRoute,
  AppRepositoriesIdChatRoute: AppRepositoriesIdChatRoute,
  AppRepositoriesIdDependenciesRoute: AppRepositoriesIdDependenciesRoute,
  AppRepositoriesIdDocumentationRoute: AppRepositoriesIdDocumentationRoute,
  AppRepositoriesIdFilesRoute: AppRepositoriesIdFilesRoute,
  AppRepositoriesIdHealthRoute: AppRepositoriesIdHealthRoute,
  AppRepositoriesIdSearchRoute: AppRepositoriesIdSearchRoute,
  AppRepositoriesIdIndexRoute: AppRepositoriesIdIndexRoute,
}

const AppRepositoriesIdRouteWithChildren =
  AppRepositoriesIdRoute._addFileChildren(AppRepositoriesIdRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppRepositoriesIdRoute: typeof AppRepositoriesIdRouteWithChildren
  AppRepositoriesIndexRoute: typeof AppRepositoriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppRepositoriesIdRoute: AppRepositoriesIdRouteWithChildren,
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ApiPublicHooksProcessAnalysisRoute: ApiPublicHooksProcessAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
